name: Junk
favicon: null
layout_spectrum: 0.35211
typography_spectrum: 0.1056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#e7e7e5'
    - '#c1b9ae'
    - '#8b5635'
    - '#284850'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
